#!/usr/bin/env bash
# VIGIL installer — idempotent, cross-host
#
# Usage:
#   bash install.sh [target-directory] [--mode=<read-only|sandbox|write>]
#
# Defaults:
#   target-directory: ./agents/vigil
#   mode:             read-only (safest default)
#
# The installer is safe to run multiple times. Existing files are preserved
# unless --force is supplied.

set -euo pipefail

# --- Defaults ---
TARGET="${1:-./agents/vigil}"
MODE="read-only"
FORCE=0

# --- Parse flags ---
for arg in "$@"; do
  case "$arg" in
    --mode=*)
      MODE="${arg#--mode=}"
      ;;
    --force)
      FORCE=1
      ;;
    --help|-h)
      sed -n '2,16p' "$0"
      exit 0
      ;;
  esac
done

# --- Validate mode ---
case "$MODE" in
  read-only|sandbox|write) ;;
  *)
    echo "ERROR: Invalid mode '$MODE'. Must be one of: read-only, sandbox, write" >&2
    exit 2
    ;;
esac

# --- Resolve VIGIL source directory ---
VIGIL_SRC="$(cd "$(dirname "$0")" && pwd)"

if [[ ! -f "${VIGIL_SRC}/VIGIL.md" ]]; then
  echo "ERROR: install.sh must be run from the VIGIL source directory (VIGIL.md not found)" >&2
  exit 3
fi

# --- Create target structure ---
echo "VIGIL installer"
echo "  source:  $VIGIL_SRC"
echo "  target:  $TARGET"
echo "  mode:    $MODE"
echo ""

mkdir -p "$TARGET"
mkdir -p "$TARGET/skills/verify"
mkdir -p "$TARGET/skills/isolate"
mkdir -p "$TARGET/skills/graph"
mkdir -p "$TARGET/skills/intervene"
mkdir -p "$TARGET/skills/learn"
mkdir -p "$TARGET/templates"
mkdir -p "$TARGET/schemas"
mkdir -p "$TARGET/hosts"
mkdir -p "$TARGET/evals/canary"

# --- Copy files (with skip-if-exists unless --force) ---
copy_file() {
  local src="$1"
  local dst="$2"
  if [[ -e "$dst" && $FORCE -eq 0 ]]; then
    echo "  skip (exists): $dst"
    return 0
  fi
  cp "$src" "$dst"
  echo "  copy: $dst"
}

# Core files
copy_file "$VIGIL_SRC/agent.md"            "$TARGET/agent.md"
copy_file "$VIGIL_SRC/VIGIL.md"            "$TARGET/VIGIL.md"
copy_file "$VIGIL_SRC/AGENTS.md"           "$TARGET/AGENTS.md"
copy_file "$VIGIL_SRC/CLAUDE.md"           "$TARGET/CLAUDE.md"
copy_file "$VIGIL_SRC/DESIGN-RATIONALE.md" "$TARGET/DESIGN-RATIONALE.md"
copy_file "$VIGIL_SRC/README.md"           "$TARGET/README.md"
copy_file "$VIGIL_SRC/CHANGELOG.md"        "$TARGET/CHANGELOG.md"

# Skills
for phase in verify isolate graph intervene learn; do
  copy_file "$VIGIL_SRC/skills/$phase/SKILL.md" "$TARGET/skills/$phase/SKILL.md"
done

# Templates
for tpl in root-cause-report verified-patch failure-signature escalation-brief; do
  copy_file "$VIGIL_SRC/templates/$tpl.md" "$TARGET/templates/$tpl.md"
done

# Schemas
for schema in reproduction intervention-log root-cause-report; do
  copy_file "$VIGIL_SRC/schemas/$schema.v1.json" "$TARGET/schemas/$schema.v1.json"
done

# Hosts
for host in claude-code cursor copilot opencode; do
  copy_file "$VIGIL_SRC/hosts/$host.md" "$TARGET/hosts/$host.md"
done

# Canary missions
if [[ -d "$VIGIL_SRC/evals/canary" ]]; then
  for f in "$VIGIL_SRC"/evals/canary/*.md; do
    [[ -e "$f" ]] || continue
    copy_file "$f" "$TARGET/evals/canary/$(basename "$f")"
  done
fi

# --- Generate per-project config ---
CONFIG_DIR="$(dirname "$TARGET")/.vigil"
if [[ ! -d "$CONFIG_DIR" ]]; then
  mkdir -p "$CONFIG_DIR"
  cat > "$CONFIG_DIR/config.yml" <<EOF
# VIGIL per-project configuration
# Generated by installer on $(date -u +%Y-%m-%dT%H:%M:%SZ)

authority:
  default_mode: $MODE
  allow_write: $([ "$MODE" = "write" ] && echo "true" || echo "false")

sandbox:
  # Choose adapter based on your project stack:
  #   docker            — most portable; requires docker daemon
  #   podman            — rootless alternative to docker
  #   language_native   — use your project's test runner (pytest, jest, rspec, cargo test)
  #   firejail          — Linux host-level sandboxing
  #   bubblewrap        — Linux host-level sandboxing (used by Flatpak)
  adapter: language_native

  # Adapter-specific settings (uncomment as needed):
  # image: python:3.12-slim              # for docker/podman
  # working_dir: /tmp/vigil-sandbox
  timeout_s: 300

  resource_limits:
    memory_mb: 2048
    cpus: 2

memory:
  path: memories/vigil-failures.yaml
  signature_cap: 50
  consolidation_strategy: recency_weighted

trace_source:
  # Optional — if project emits OTEL GenAI traces, VIGIL can consume them
  # directly in Phase G for IDG construction.
  type: none                             # none | otel | otlp_file | structured_log
  # endpoint: http://localhost:4318
  # retention_days: 7

# Integration with other Eidolons (paths relative to project root).
# Uncomment what applies:
# eidolons:
#   apivr_delta: agents/apivr/
#   spectra:     agents/spectra/
#   atlas:       agents/atlas/
#   idg:         agents/idg/
#   forge:       agents/forge/
EOF
  echo "  generated: $CONFIG_DIR/config.yml"
fi

# --- Memory ledger placeholder ---
MEM_DIR="$(dirname "$TARGET")/memories"
if [[ ! -e "$MEM_DIR/vigil-failures.yaml" ]]; then
  mkdir -p "$MEM_DIR"
  cat > "$MEM_DIR/vigil-failures.yaml" <<EOF
# VIGIL failure signature ledger
# Managed automatically by VIGIL Phase L
# Consolidated opportunistically at end of each mission
# Soft cap: 50 entries — older single-occurrence entries archive to vigil-failures.archive.yaml

version: "1.0"
methodology: VIGIL
signatures: []
EOF
  echo "  generated: $MEM_DIR/vigil-failures.yaml"
fi

# --- Post-install summary ---
echo ""
echo "VIGIL installed at: $TARGET"
echo "Config at:          $CONFIG_DIR/config.yml"
echo "Memory at:          $MEM_DIR/vigil-failures.yaml"
echo ""
echo "Next steps:"
echo "  1. Review $CONFIG_DIR/config.yml — choose your sandbox adapter"
echo "  2. Point your AI host at $TARGET/agent.md — see hosts/ for per-host wiring"
echo "  3. Run the canary evaluation:"
echo "       cd $TARGET && ls evals/canary/"
echo ""
echo "Mode is '$MODE'. To change:"
echo "  - Edit $CONFIG_DIR/config.yml, OR"
echo "  - Re-run installer with --mode=<new-mode> --force"
echo ""
